spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: lb://USER
          predicates:
          - Path=/fetch
          filters:
          - name: CircuitBreaker
            args:
              name: slow
#          metadata:
#            response-timeout: 1000

server:
  port: 80
logging:
  level:
    org.springframework.cloud.gateway: trace
