spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: test
          predicates:
            - Path=/fetch
          uri: http://localhost:8081

server:
  port: 80
logging:
  level:
    org.springframework.cloud.gateway: trace
