{
  parserClass="com.emptycastle.customlanguage.parser.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="com.emptycastle.customlanguage.psi"
  psiImplPackage="com.emptycastle.customlanguage.psi.impl"

  elementTypeHolderClass="com.emptycastle.customlanguage.psi.SimpleTypes"
  elementTypeClass="com.emptycastle.customlanguage.psi.SimpleElementType"
  tokenTypeClass="com.emptycastle.customlanguage.psi.SimpleTokenType"

  psiImplUtilClass="com.emptycastle.customlanguage.psi.impl.SimplePsiImplUtil"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY {
    mixin="com.emptycastle.customlanguage.psi.impl.SimpleNamedElementImpl"
    implements="com.emptycastle.customlanguage.psi.SimpleNamedElement"
    methods=[getKey getValue getName setName getNameIdentifier getPresentation]
}